### ISSUE TITLE
El scrol no permite deslizar hasta el ulttimo elemento del sidebar

### ISSUE THREAD

**Issue by BruteForceSolutionsSRL** [BruteForceSolutionsSRL/reservation-system-front#99]
![WhatsApp Image 2024-07-01 at 01 43 25](https://github.com/BruteForceSolutionsSRL/reservation-system-front/assets/163222463/03735a61-3ed2-4410-87d0-aadc500962c2)

**Comment by Sega1A** [comment]
Corregido.
